version: "3"

services:
  app:
    image: davidavidavid/pizza-management:latest
    depends_on:
      - db
    environment:
      - DB_URI=mongodb://172.17.0.1:27017/report
  db:
    image: mongo:4.0
    ports:
      - "27017:27017"
